version: '2'
services:
  more-tacos:
    build:
      dockerfile: Dockerfile
      context: .
    image: devprogress/more-tacos:latest
    command: npm run gulp-watch
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/more-tacos
